### ISSUE TITLE
Adding SSL Support to the WebServer

### ISSUE THREAD

**Issue by iShafayet** [shihabahmed/demo-chat-server-with-push-notification#1]
It can be achieved by overriding the WebServer class. If you look into the implementation inside evolvenode's web.coffee, the answer is pretty straightforward. 

*This is actually a good practice when dealing with OOP in general and especially coffee-script. Due to the flexible nature of javascript `type`s, it can be tempting to try and modify existing objects. But doing so may break stuff elsewhere.*

*So, basically, when you need to add additional feature to a class, use `extend` and shoot your own.*

```
###
  @class SecureWebServer
###

## NOTE the class WebServer is the one from evolvenode

class SecureWebServer extends WebServer

  start: ()->
    
    options = 
      ca: '..'
      key: '..'
      cert: '..'

    @nodeServer = (require 'https').createServer options, @_handleNodeServerRequest
    if @host
      @nodeServer.listen @port, @host, =>
        @emit 'start'
    else
      @nodeServer.listen @port, =>
        @emit 'start'
```

**Comment by shihabahmed** [comment]
Thanks a lot for the guidance. It helped a lot.
